[workspace]
description = "Banjo provides TUI building blocks in Mojo."
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://conda.modular.com/max", "conda-forge"]
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/thatstoasty/banjo"
repository = "https://github.com/thatstoasty/banjo"
preview = ["pixi-build"]

[tasks]
tests = "sh -c 'find test -name \"test_*.mojo\" -exec mojo -D ASSERT=all -I . {} \\;'"
examples = "sh -c 'find examples -name \"*.mojo\" -exec mojo -D ASSERT=all -I . {} \\;'"

# Linting and Formatting
lint_docs = "mojo doc --Werror --diagnose-missing-doc-strings -o /dev/null ./banjo"
mojo_format = "mojo format banjo --line-length 120"
format = [{ task = "mojo_format" }]

[package]
name = "banjo"
version = "0.0.1"

[package.build]
backend = { name = "pixi-build-mojo", version = "0.*" }

[dependencies]
mojo = ">=1.0.0,<1.1.0"
mog = { git = "https://github.com/thatstoasty/mog.git", tag = "v0.3.1" }
termctl = { path = "../termctl" }

[package.build-dependencies]
mojo-compiler = ">=1.0.0,<1.1.0"
mog = { git = "https://github.com/thatstoasty/mog.git", tag = "v0.3.1" }
termctl = { path = "../termctl" }

[package.host-dependencies]
mojo-compiler = ">=1.0.0,<1.1.0"

[package.run-dependencies]
mojo = ">=1.0.0,<1.1.0"
mog = { git = "https://github.com/thatstoasty/mog.git", tag = "v0.3.1" }
termctl = { path = "../termctl" }
